/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserTrainingRouteImport } from './routes/user/training'
import { Route as UserRulesRouteImport } from './routes/user/rules'
import { Route as UserHomeRouteImport } from './routes/user/home'
import { Route as UserEncodeRouteImport } from './routes/user/encode'
import { Route as UserDecodeRouteImport } from './routes/user/decode'
import { Route as AdminTrainingRouteImport } from './routes/admin/training'
import { Route as AdminRulesRouteImport } from './routes/admin/rules'
import { Route as AdminHomeRouteImport } from './routes/admin/home'
import { Route as AdminEncodeRouteImport } from './routes/admin/encode'
import { Route as AdminDecodeRouteImport } from './routes/admin/decode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserTrainingRoute = UserTrainingRouteImport.update({
  id: '/user/training',
  path: '/user/training',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRulesRoute = UserRulesRouteImport.update({
  id: '/user/rules',
  path: '/user/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const UserHomeRoute = UserHomeRouteImport.update({
  id: '/user/home',
  path: '/user/home',
  getParentRoute: () => rootRouteImport,
} as any)
const UserEncodeRoute = UserEncodeRouteImport.update({
  id: '/user/encode',
  path: '/user/encode',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDecodeRoute = UserDecodeRouteImport.update({
  id: '/user/decode',
  path: '/user/decode',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrainingRoute = AdminTrainingRouteImport.update({
  id: '/admin/training',
  path: '/admin/training',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRulesRoute = AdminRulesRouteImport.update({
  id: '/admin/rules',
  path: '/admin/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/admin/home',
  path: '/admin/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEncodeRoute = AdminEncodeRouteImport.update({
  id: '/admin/encode',
  path: '/admin/encode',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDecodeRoute = AdminDecodeRouteImport.update({
  id: '/admin/decode',
  path: '/admin/decode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/decode': typeof AdminDecodeRoute
  '/admin/encode': typeof AdminEncodeRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/training': typeof AdminTrainingRoute
  '/user/decode': typeof UserDecodeRoute
  '/user/encode': typeof UserEncodeRoute
  '/user/home': typeof UserHomeRoute
  '/user/rules': typeof UserRulesRoute
  '/user/training': typeof UserTrainingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/decode': typeof AdminDecodeRoute
  '/admin/encode': typeof AdminEncodeRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/training': typeof AdminTrainingRoute
  '/user/decode': typeof UserDecodeRoute
  '/user/encode': typeof UserEncodeRoute
  '/user/home': typeof UserHomeRoute
  '/user/rules': typeof UserRulesRoute
  '/user/training': typeof UserTrainingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/decode': typeof AdminDecodeRoute
  '/admin/encode': typeof AdminEncodeRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/training': typeof AdminTrainingRoute
  '/user/decode': typeof UserDecodeRoute
  '/user/encode': typeof UserEncodeRoute
  '/user/home': typeof UserHomeRoute
  '/user/rules': typeof UserRulesRoute
  '/user/training': typeof UserTrainingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/decode'
    | '/admin/encode'
    | '/admin/home'
    | '/admin/rules'
    | '/admin/training'
    | '/user/decode'
    | '/user/encode'
    | '/user/home'
    | '/user/rules'
    | '/user/training'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/decode'
    | '/admin/encode'
    | '/admin/home'
    | '/admin/rules'
    | '/admin/training'
    | '/user/decode'
    | '/user/encode'
    | '/user/home'
    | '/user/rules'
    | '/user/training'
  id:
    | '__root__'
    | '/'
    | '/admin/decode'
    | '/admin/encode'
    | '/admin/home'
    | '/admin/rules'
    | '/admin/training'
    | '/user/decode'
    | '/user/encode'
    | '/user/home'
    | '/user/rules'
    | '/user/training'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDecodeRoute: typeof AdminDecodeRoute
  AdminEncodeRoute: typeof AdminEncodeRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminRulesRoute: typeof AdminRulesRoute
  AdminTrainingRoute: typeof AdminTrainingRoute
  UserDecodeRoute: typeof UserDecodeRoute
  UserEncodeRoute: typeof UserEncodeRoute
  UserHomeRoute: typeof UserHomeRoute
  UserRulesRoute: typeof UserRulesRoute
  UserTrainingRoute: typeof UserTrainingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/training': {
      id: '/user/training'
      path: '/user/training'
      fullPath: '/user/training'
      preLoaderRoute: typeof UserTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/rules': {
      id: '/user/rules'
      path: '/user/rules'
      fullPath: '/user/rules'
      preLoaderRoute: typeof UserRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/home': {
      id: '/user/home'
      path: '/user/home'
      fullPath: '/user/home'
      preLoaderRoute: typeof UserHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/encode': {
      id: '/user/encode'
      path: '/user/encode'
      fullPath: '/user/encode'
      preLoaderRoute: typeof UserEncodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/decode': {
      id: '/user/decode'
      path: '/user/decode'
      fullPath: '/user/decode'
      preLoaderRoute: typeof UserDecodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/training': {
      id: '/admin/training'
      path: '/admin/training'
      fullPath: '/admin/training'
      preLoaderRoute: typeof AdminTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rules': {
      id: '/admin/rules'
      path: '/admin/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/admin/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/encode': {
      id: '/admin/encode'
      path: '/admin/encode'
      fullPath: '/admin/encode'
      preLoaderRoute: typeof AdminEncodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/decode': {
      id: '/admin/decode'
      path: '/admin/decode'
      fullPath: '/admin/decode'
      preLoaderRoute: typeof AdminDecodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDecodeRoute: AdminDecodeRoute,
  AdminEncodeRoute: AdminEncodeRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminRulesRoute: AdminRulesRoute,
  AdminTrainingRoute: AdminTrainingRoute,
  UserDecodeRoute: UserDecodeRoute,
  UserEncodeRoute: UserEncodeRoute,
  UserHomeRoute: UserHomeRoute,
  UserRulesRoute: UserRulesRoute,
  UserTrainingRoute: UserTrainingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
